version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "9000:9000"
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - REDIS_HOST=redis
        depends_on:
            - db
            - redis
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: laravel_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - app-network

    worker:
        build:
            context: .
        container_name: laravel_worker
        depends_on:
            - app
        volumes:
            - .:/var/www
        working_dir: /var/www
        command: php artisan queue:work --tries=3 --timeout=90
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
